
-- Limpar dados existentes e recriar a estrutura de leitos conforme especificado
DELETE FROM bed_reservations;
DELETE FROM patients;
DELETE FROM beds;

-- CLÍNICA MÉDICA - 40 leitos
INSERT INTO beds (name, department, is_occupied, is_reserved, is_custom) VALUES
  ('ISOL', 'CLINICA MEDICA', false, false, false),
  ('2A', 'CLINICA MEDICA', false, false, false),
  ('2B', 'CLINICA MEDICA', false, false, false),
  ('2C', 'CLINICA MEDICA', false, false, false),
  ('2D', 'CLINICA MEDICA', false, false, false),
  ('3A', 'CLINICA MEDICA', false, false, false),
  ('3B', 'CLINICA MEDICA', false, false, false),
  ('3C', 'CLINICA MEDICA', false, false, false),
  ('4A', 'CLINICA MEDICA', false, false, false),
  ('4B', 'CLINICA MEDICA', false, false, false),
  ('6A', 'CLINICA MEDICA', false, false, false),
  ('6B', 'CLINICA MEDICA', false, false, false),
  ('7A', 'CLINICA MEDICA', false, false, false),
  ('7B', 'CLINICA MEDICA', false, false, false),
  ('8A', 'CLINICA MEDICA', false, false, false),
  ('8B', 'CLINICA MEDICA', false, false, false),
  ('9A', 'CLINICA MEDICA', false, false, false),
  ('9B', 'CLINICA MEDICA', false, false, false),
  ('10A', 'CLINICA MEDICA', false, false, false),
  ('10B', 'CLINICA MEDICA', false, false, false),
  ('11A', 'CLINICA MEDICA', false, false, false),
  ('11B', 'CLINICA MEDICA', false, false, false),
  ('12A', 'CLINICA MEDICA', false, false, false),
  ('12B', 'CLINICA MEDICA', false, false, false),
  ('13A', 'CLINICA MEDICA', false, false, false),
  ('13B', 'CLINICA MEDICA', false, false, false),
  ('14A', 'CLINICA MEDICA', false, false, false),
  ('14B', 'CLINICA MEDICA', false, false, false),
  ('14C', 'CLINICA MEDICA', false, false, false),
  ('14D', 'CLINICA MEDICA', false, false, false),
  ('15A', 'CLINICA MEDICA', false, false, false),
  ('15B', 'CLINICA MEDICA', false, false, false),
  ('15C', 'CLINICA MEDICA', false, false, false),
  ('16A', 'CLINICA MEDICA', false, false, false),
  ('16B', 'CLINICA MEDICA', false, false, false),
  ('16C', 'CLINICA MEDICA', false, false, false),
  ('17A', 'CLINICA MEDICA', false, false, false),
  ('17B', 'CLINICA MEDICA', false, false, false),
  ('17C', 'CLINICA MEDICA', false, false, false),
  ('18', 'CLINICA MEDICA', false, false, false);

-- PRONTO SOCORRO - 31 leitos
INSERT INTO beds (name, department, is_occupied, is_reserved, is_custom) VALUES
  ('1A', 'PRONTO SOCORRO', false, false, false),
  ('1B', 'PRONTO SOCORRO', false, false, false),
  ('1C', 'PRONTO SOCORRO', false, false, false),
  ('1D', 'PRONTO SOCORRO', false, false, false),
  ('2A', 'PRONTO SOCORRO', false, false, false),
  ('2B', 'PRONTO SOCORRO', false, false, false),
  ('2C', 'PRONTO SOCORRO', false, false, false),
  ('2D', 'PRONTO SOCORRO', false, false, false),
  ('2E', 'PRONTO SOCORRO', false, false, false),
  ('3A', 'PRONTO SOCORRO', false, false, false),
  ('3B', 'PRONTO SOCORRO', false, false, false),
  ('3C', 'PRONTO SOCORRO', false, false, false),
  ('3D', 'PRONTO SOCORRO', false, false, false),
  ('4A', 'PRONTO SOCORRO', false, false, false),
  ('4B', 'PRONTO SOCORRO', false, false, false),
  ('4C', 'PRONTO SOCORRO', false, false, false),
  ('4D', 'PRONTO SOCORRO', false, false, false),
  ('5A', 'PRONTO SOCORRO', false, false, false),
  ('5B', 'PRONTO SOCORRO', false, false, false),
  ('5C', 'PRONTO SOCORRO', false, false, false),
  ('BOX-1', 'PRONTO SOCORRO', false, false, false),
  ('BOX-2', 'PRONTO SOCORRO', false, false, false),
  ('BOX-3', 'PRONTO SOCORRO', false, false, false),
  ('BOX-4', 'PRONTO SOCORRO', false, false, false),
  ('BOX-5', 'PRONTO SOCORRO', false, false, false),
  ('CI-1', 'PRONTO SOCORRO', false, false, false),
  ('CI-2', 'PRONTO SOCORRO', false, false, false),
  ('CI-3', 'PRONTO SOCORRO', false, false, false),
  ('CI-4', 'PRONTO SOCORRO', false, false, false),
  ('Isolamento', 'PRONTO SOCORRO', false, false, false);

-- CLÍNICA CIRÚRGICA - 26 leitos
INSERT INTO beds (name, department, is_occupied, is_reserved, is_custom) VALUES
  ('1A - ORTOP', 'CLINICA CIRURGICA', false, false, false),
  ('1B - ORTOP', 'CLINICA CIRURGICA', false, false, false),
  ('1C - ORTOP', 'CLINICA CIRURGICA', false, false, false),
  ('2A - ORTOP', 'CLINICA CIRURGICA', false, false, false),
  ('2B - ORTOP', 'CLINICA CIRURGICA', false, false, false),
  ('2C - ORTOP', 'CLINICA CIRURGICA', false, false, false),
  ('3A - ORTOP', 'CLINICA CIRURGICA', false, false, false),
  ('3B - ORTOP', 'CLINICA CIRURGICA', false, false, false),
  ('4A - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('4B - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('5A - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('5B - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('7A - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('7B - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('7C - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('8A - ORTOP', 'CLINICA CIRURGICA', false, false, false),
  ('8B - ORTOP', 'CLINICA CIRURGICA', false, false, false),
  ('8C - ORTOP', 'CLINICA CIRURGICA', false, false, false),
  ('9A - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('9B - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('9C - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('10A - PED', 'CLINICA CIRURGICA', false, false, false),
  ('10B - PED', 'CLINICA CIRURGICA', false, false, false),
  ('11A - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('11B - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('11C - CIRUR', 'CLINICA CIRURGICA', false, false, false),
  ('Isolamento', 'CLINICA CIRURGICA', false, false, false);

-- UTI ADULTO - 16 leitos
INSERT INTO beds (name, department, is_occupied, is_reserved, is_custom) VALUES
  ('BOX - 1', 'UTI ADULTO', false, false, false),
  ('BOX - 2', 'UTI ADULTO', false, false, false),
  ('BOX - 3', 'UTI ADULTO', false, false, false),
  ('BOX - 4', 'UTI ADULTO', false, false, false),
  ('BOX - 5', 'UTI ADULTO', false, false, false),
  ('BOX - 6', 'UTI ADULTO', false, false, false),
  ('BOX - 7', 'UTI ADULTO', false, false, false),
  ('BOX - 8', 'UTI ADULTO', false, false, false),
  ('BOX - 9', 'UTI ADULTO', false, false, false),
  ('BOX - 10', 'UTI ADULTO', false, false, false),
  ('BOX - 11', 'UTI ADULTO', false, false, false),
  ('BOX - 12', 'UTI ADULTO', false, false, false),
  ('BOX - 13', 'UTI ADULTO', false, false, false),
  ('BOX - 14', 'UTI ADULTO', false, false, false),
  ('BOX - 15 - ISOL', 'UTI ADULTO', false, false, false),
  ('BOX - 16 - ISOL', 'UTI ADULTO', false, false, false);

-- UTI NEONATAL - 8 leitos
INSERT INTO beds (name, department, is_occupied, is_reserved, is_custom) VALUES
  ('1A', 'UTI NEONATAL', false, false, false),
  ('1B', 'UTI NEONATAL', false, false, false),
  ('1C', 'UTI NEONATAL', false, false, false),
  ('1D', 'UTI NEONATAL', false, false, false),
  ('Canguru-2A', 'UTI NEONATAL', false, false, false),
  ('Canguru-2B', 'UTI NEONATAL', false, false, false),
  ('Convencional 1', 'UTI NEONATAL', false, false, false),
  ('Convencional 2', 'UTI NEONATAL', false, false, false);

-- PEDIATRIA - 27 leitos
INSERT INTO beds (name, department, is_occupied, is_reserved, is_custom) VALUES
  ('BOX-1', 'PEDIATRIA', false, false, false),
  ('BOX-2', 'PEDIATRIA', false, false, false),
  ('BOX-3', 'PEDIATRIA', false, false, false),
  ('BOX-4', 'PEDIATRIA', false, false, false),
  ('1A', 'PEDIATRIA', false, false, false),
  ('1B', 'PEDIATRIA', false, false, false),
  ('1C', 'PEDIATRIA', false, false, false),
  ('1D', 'PEDIATRIA', false, false, false),
  ('2A', 'PEDIATRIA', false, false, false),
  ('2B', 'PEDIATRIA', false, false, false),
  ('2C', 'PEDIATRIA', false, false, false),
  ('2D', 'PEDIATRIA', false, false, false),
  ('2E', 'PEDIATRIA', false, false, false),
  ('3A', 'PEDIATRIA', false, false, false),
  ('3B', 'PEDIATRIA', false, false, false),
  ('3C', 'PEDIATRIA', false, false, false),
  ('3D', 'PEDIATRIA', false, false, false),
  ('4A', 'PEDIATRIA', false, false, false),
  ('4B', 'PEDIATRIA', false, false, false),
  ('4C', 'PEDIATRIA', false, false, false),
  ('4D', 'PEDIATRIA', false, false, false),
  ('5A', 'PEDIATRIA', false, false, false),
  ('5B', 'PEDIATRIA', false, false, false),
  ('5C', 'PEDIATRIA', false, false, false),
  ('Isolamento', 'PEDIATRIA', false, false, false);

-- MATERNIDADE - 30 leitos
INSERT INTO beds (name, department, is_occupied, is_reserved, is_custom) VALUES
  ('1A', 'MATERNIDADE', false, false, false),
  ('1B', 'MATERNIDADE', false, false, false),
  ('2A', 'MATERNIDADE', false, false, false),
  ('2B', 'MATERNIDADE', false, false, false),
  ('4A', 'MATERNIDADE', false, false, false),
  ('4B', 'MATERNIDADE', false, false, false),
  ('5A', 'MATERNIDADE', false, false, false),
  ('5B', 'MATERNIDADE', false, false, false),
  ('6A', 'MATERNIDADE', false, false, false),
  ('6B', 'MATERNIDADE', false, false, false),
  ('7A', 'MATERNIDADE', false, false, false),
  ('7B', 'MATERNIDADE', false, false, false),
  ('9A', 'MATERNIDADE', false, false, false),
  ('9B', 'MATERNIDADE', false, false, false),
  ('9C', 'MATERNIDADE', false, false, false),
  ('10A', 'MATERNIDADE', false, false, false),
  ('10B', 'MATERNIDADE', false, false, false),
  ('10C', 'MATERNIDADE', false, false, false),
  ('11A', 'MATERNIDADE', false, false, false),
  ('11B', 'MATERNIDADE', false, false, false),
  ('11C', 'MATERNIDADE', false, false, false),
  ('BOX-A', 'MATERNIDADE', false, false, false),
  ('CI-A', 'MATERNIDADE', false, false, false),
  ('CI-B', 'MATERNIDADE', false, false, false),
  ('Ind. A', 'MATERNIDADE', false, false, false),
  ('Ind. B', 'MATERNIDADE', false, false, false),
  ('ISOL', 'MATERNIDADE', false, false, false),
  ('PP-1', 'MATERNIDADE', false, false, false),
  ('PP-2', 'MATERNIDADE', false, false, false),
  ('PP-3', 'MATERNIDADE', false, false, false);
