
-- Adicionar campos SETOR e LEITO na tabela ambulance_requests
ALTER TABLE public.ambulance_requests 
ADD COLUMN sector TEXT,
ADD COLUMN bed TEXT;

-- Inserir mais cidades de Minas Gerais (lista mais completa, corrigindo caracteres especiais)
INSERT INTO public.mg_cities (name) VALUES 
('Abadia dos Dourados'),
('Abaeté'),
('Abre Campo'),
('Acaiaca'),
('Aimorés'),
('Aiuruoca'),
('Alagoa'),
('Albertina'),
('Além Paraíba'),
('Alfredo Vasconcelos'),
('Alvorada de Minas'),
('Amparo do Serra'),
('Andrelândia'),
('Antônio Carlos'),
('Antônio Dias'),
('Antônio Prado de Minas'),
('Araçaí'),
('Aracitaba'),
('Araújos'),
('Arceburgo'),
('Arcos'),
('Areado'),
('Argirita'),
('Astolfo Dutra'),
('Ataléia'),
('Augusto de Lima'),
('Baependi'),
('Baldim'),
('Bandeira'),
('Bandeira do Sul'),
('Barão de Cocais'),
('Barão de Monte Alto'),
('Barbosa'),
('Barra Longa'),
('Barroso'),
('Bela Vista de Minas'),
('Belmiro Braga'),
('Belo Oriente'),
('Belo Vale'),
('Berilo'),
('Berizal'),
('Bertópolis'),
('Bias Fortes'),
('Bicas'),
('Biquinhas'),
('Bocaina de Minas'),
('Bom Despacho'),
('Bom Jardim de Minas'),
('Bom Jesus da Penha'),
('Bom Jesus do Amparo'),
('Bom Jesus do Galho'),
('Bom Repouso'),
('Bom Sucesso'),
('Bonfim'),
('Bonfinópolis de Minas'),
('Bonito de Minas'),
('Borda da Mata'),
('Botelhos'),
('Botumirim'),
('Brás Pires'),
('Brasilândia de Minas'),
('Brasília de Minas'),
('Brasópolis'),
('Braúnas'),
('Brumadinho'),
('Bueno Brandão'),
('Buenópolis'),
('Bugre'),
('Cachoeira da Prata'),
('Cachoeira de Minas'),
('Cachoeira de Pajeú'),
('Cachoeira Dourada'),
('Caetanópolis'),
('Caieiras'),
('Cajuri'),
('Caldas'),
('Camacho'),
('Camanducaia'),
('Cambuí'),
('Cambuquira'),
('Campanário'),
('Campeche'),
('Campestre'),
('Campina Verde'),
('Campo Azul'),
('Campo do Meio'),
('Campos Altos'),
('Campos Gerais'),
('Cana Verde'),
('Canaã'),
('Canápolis'),
('Candeias'),
('Cantagalo'),
('Caparaó'),
('Capela Nova'),
('Capelinha'),
('Capetinga'),
('Capim Branco'),
('Capinópolis'),
('Capitão Andrade'),
('Capitão Enéas'),
('Caputira'),
('Caraí'),
('Caranaíba'),
('Carandaí'),
('Carbonita'),
('Careaçu'),
('Carlos Chagas'),
('Carmésia'),
('Carmo da Cachoeira'),
('Carmo da Mata'),
('Carmo de Minas'),
('Carmo do Paranaíba'),
('Carmo do Rio Claro'),
('Carmópolis de Minas'),
('Carneirinho'),
('Carrancas'),
('Carvalhópolis'),
('Carvalhos'),
('Casa Grande'),
('Cascalho Rico'),
('Cássia'),
('Catas Altas'),
('Catas Altas da Noruega'),
('Catuji'),
('Catuti'),
('Caxambu'),
('Cedro do Abaeté'),
('Central de Minas'),
('Centralina'),
('Chácara'),
('Chalé'),
('Chapada do Norte'),
('Chapada Gaúcha'),
('Chiador'),
('Cipotânea'),
('Claraval'),
('Claro dos Poções'),
('Cláudio'),
('Coimbra'),
('Coluna'),
('Comendador Gomes'),
('Comercinho'),
('Conceição da Barra de Minas'),
('Conceição das Alagoas'),
('Conceição das Pedras'),
('Conceição de Ipanema'),
('Conceição do Pará'),
('Conceição do Rio Verde'),
('Conceição dos Ouros'),
('Cônego Marinho'),
('Confins'),
('Congonhal'),
('Congonhas do Norte'),
('Conquista'),
('Conselheiro Pena'),
('Consolação'),
('Coqueiral'),
('Coração de Jesus'),
('Cordisburgo'),
('Cordislândia'),
('Corinto'),
('Coroaci'),
('Coromandel'),
('Coronel Murta'),
('Coronel Pacheco'),
('Córrego Danta'),
('Córrego do Bom Jesus'),
('Córrego Fundo'),
('Córrego Novo'),
('Couto de Magalhães de Minas'),
('Crisólita'),
('Cristais'),
('Cristália'),
('Cristiano Otoni'),
('Cristina'),
('Crucilândia'),
('Cruzeiro da Fortaleza'),
('Cruzília'),
('Cuparaque'),
('Curral de Dentro'),
('Datas'),
('Delfim Moreira'),
('Delfinópolis'),
('Delta'),
('Descoberto'),
('Desterro de Entre Rios'),
('Desterro do Melo'),
('Diogo de Vasconcelos'),
('Dionísio'),
('Divinésia'),
('Divino'),
('Divino das Laranjeiras'),
('Divinolândia de Minas'),
('Divisa Alegre'),
('Divisa Nova'),
('Divisópolis'),
('Dom Bosco'),
('Dom Cavati'),
('Dom Joaquim'),
('Dom Silvério'),
('Dom Viçoso'),
('Dona Eusébia'),
('Dores de Campos'),
('Dores de Guanhães'),
('Dores do Indaiá'),
('Dores do Turvo'),
('Doresópolis'),
('Douradoquara'),
('Durandé'),
('Elói Mendes'),
('Engenheiro Caldas'),
('Engenheiro Navarro'),
('Entre Folhas'),
('Entre Rios de Minas'),
('Ervália'),
('Espera Feliz'),
('Espírito Santo do Dourado'),
('Estiva'),
('Estrela Dalva'),
('Estrela do Indaiá'),
('Estrela do Sul'),
('Eugenópolis'),
('Ewbank da Câmara'),
('Fama'),
('Faria Lemos'),
('Felício dos Santos'),
('Felisburgo'),
('Felixlândia'),
('Fernandes Tourinho'),
('Ferros'),
('Fervedouro'),
('Florestal'),
('Formoso'),
('Fortaleza de Minas'),
('Fortuna de Minas'),
('Francisco Badaró'),
('Francisco Dumont'),
('Francisco Sá'),
('Franciscópolis'),
('Frei Gaspar'),
('Frei Inocêncio'),
('Frei Lagonegro'),
('Fronteira'),
('Fronteira dos Vales'),
('Fruta de Leite'),
('Funilândia'),
('Galiléia'),
('Gameleiras'),
('Glaucilândia'),
('Goiabeira'),
('Goianá'),
('Gonçalves'),
('Gonzaga'),
('Gouveia'),
('Grão Mogol'),
('Grupiara'),
('Guanhães'),
('Guapé'),
('Guaraciaba'),
('Guaraciama'),
('Guaranésia'),
('Guarani'),
('Guarará'),
('Guarda-Mor'),
('Guidoval'),
('Guimarânia'),
('Guiricema'),
('Gurinhatã'),
('Heliodora'),
('Iapu'),
('Ibertioga'),
('Ibiá'),
('Ibiaí'),
('Ibiracatu'),
('Ibiraci'),
('Ibitiúra de Minas'),
('Ibituruna'),
('Icaraí de Minas'),
('Igarapé'),
('Igaratinga'),
('Iguatama'),
('Ijaci'),
('Ilicínea'),
('Imbé de Minas'),
('Inconfidentes'),
('Indaiabira'),
('Indianópolis'),
('Ingaí'),
('Inhapim'),
('Inhaúma'),
('Inimutaba'),
('Ipaba'),
('Ipanema'),
('Ipiaçu'),
('Ipuiúna'),
('Iraí de Minas'),
('Itabirinha'),
('Itabirito'),
('Itacambira'),
('Itacarambi'),
('Itaguara'),
('Itaipé'),
('Itamarandiba'),
('Itamarati de Minas'),
('Itambacuri'),
('Itambé do Mato Dentro'),
('Itamogi'),
('Itamonte'),
('Itanhandu'),
('Itanhomi'),
('Itaobim'),
('Itapagipe'),
('Itapecerica'),
('Itapeva'),
('Itatiaiuçu'),
('Itaú de Minas'),
('Itaverava'),
('Itinga'),
('Itueta'),
('Itumirim'),
('Iturama'),
('Itutinga'),
('Jaboticatubas'),
('Jacuí'),
('Jacutinga'),
('Jaguaraçu'),
('Jaíba'),
('Jampruca'),
('Japonvar'),
('Jeceaba'),
('Jenipapo de Minas'),
('Jequeri'),
('Jequitaí'),
('Jequitibá'),
('Jequitinhonha'),
('Jesuânia'),
('Joaíma'),
('Joanésia'),
('João Pinheiro'),
('Joaquim Felício'),
('Jordânia'),
('José Gonçalves de Minas'),
('José Raydan'),
('Josenópolis'),
('Juatuba'),
('Juramento'),
('Juruaia'),
('Juvenília'),
('Ladainha'),
('Lagamar'),
('Lagoa da Prata'),
('Lagoa dos Patos'),
('Lagoa Dourada'),
('Lagoa Formosa'),
('Lagoa Grande'),
('Lajinha'),
('Lambari'),
('Lamim'),
('Laranjal'),
('Lassance'),
('Leandro Ferreira'),
('Leme do Prado'),
('Liberdade'),
('Lima Duarte'),
('Limeira do Oeste'),
('Lontra'),
('Luisburgo'),
('Luislândia'),
('Luminárias'),
('Luz'),
('Machacalis'),
('Madre de Deus de Minas'),
('Malacacheta'),
('Mamonas'),
('Manga'),
('Manhumirim'),
('Mantena'),
('Mar de Espanha'),
('Maravilhas'),
('Maria da Fé'),
('Marilac'),
('Mário Campos'),
('Maripá de Minas'),
('Marliéria'),
('Marmelópolis'),
('Martinho Campos'),
('Martins Soares'),
('Mata Verde'),
('Materlândia'),
('Mateus Leme'),
('Mathias Lobato'),
('Matias Barbosa'),
('Matias Cardoso'),
('Matipó'),
('Mato Verde'),
('Matozinhos'),
('Matutina'),
('Medeiros'),
('Medina'),
('Mendes Pimentel'),
('Mercês'),
('Mesquita'),
('Minas Novas'),
('Minduri'),
('Mirabela'),
('Miradouro'),
('Miraí'),
('Miravânia'),
('Moeda'),
('Moema'),
('Monjolos'),
('Monsenhor Paulo'),
('Montalvânia'),
('Monte Alegre de Minas'),
('Monte Azul'),
('Monte Belo'),
('Monte Formoso'),
('Monte Santo de Minas'),
('Monte Sião'),
('Montezuma'),
('Morada Nova de Minas'),
('Morro da Garça'),
('Morro do Pilar'),
('Munhoz'),
('Mutum'),
('Muzambinho'),
('Nacip Raydan'),
('Naque'),
('Natalândia'),
('Natércia'),
('Nazareno'),
('Ninheira'),
('Nova Belém'),
('Nova Era'),
('Nova Módica'),
('Nova Ponte'),
('Nova Porteirinha'),
('Nova Resende'),
('Nova União'),
('Novo Cruzeiro'),
('Novo Oriente de Minas'),
('Novorizonte'),
('Olaria'),
('Olhos d''Água'),
('Olímpio Noronha'),
('Oliveira Fortes'),
('Onça de Pitangui'),
('Oratórios'),
('Orizânia'),
('Ouro Branco'),
('Ouro Fino'),
('Ouro Verde de Minas'),
('Padre Carvalho'),
('Padre Paraíso'),
('Pai Pedro'),
('Paineiras'),
('Pains'),
('Palma'),
('Palmópolis'),
('Papagaios'),
('Paraguaçu'),
('Paraisópolis'),
('Paraopeba'),
('Passa Quatro'),
('Passa Tempo'),
('Passa-Vinte'),
('Passabém'),
('Patis'),
('Patrocínio do Muriaé'),
('Paula Cândido'),
('Paulistas'),
('Pavão'),
('Peçanha'),
('Pedra Azul'),
('Pedra Bonita'),
('Pedra do Anta'),
('Pedra do Indaiá'),
('Pedra Dourada'),
('Pedralva'),
('Pedras de Maria da Cruz'),
('Pedrinópolis'),
('Pedro Teixeira'),
('Pequeri'),
('Pequi'),
('Perdigão'),
('Perdões'),
('Periquito'),
('Pescador'),
('Piau'),
('Piedade de Caratinga'),
('Piedade de Ponte Nova'),
('Piedade do Rio Grande'),
('Piedade dos Gerais'),
('Pimenta'),
('Pingo d''Água'),
('Pintópolis'),
('Piracema'),
('Pirajuba'),
('Piranga'),
('Piranguçu'),
('Piranguinho'),
('Pirapetinga'),
('Piraúba'),
('Pitangui'),
('Piumhi'),
('Planura'),
('Poço Fundo'),
('Pocrane'),
('Pompéu'),
('Ponto Chique'),
('Ponto dos Volantes'),
('Porto Firme'),
('Poté'),
('Pouso Alto'),
('Prados'),
('Prata'),
('Pratápolis'),
('Pratinha'),
('Presidente Bernardes'),
('Presidente Juscelino'),
('Presidente Kubitschek'),
('Presidente Olegário'),
('Prudente de Morais'),
('Quartel Geral'),
('Queluzito'),
('Raposos'),
('Raul Soares'),
('Recreio'),
('Reduto'),
('Resende Costa'),
('Resplendor'),
('Ressaquinha'),
('Riachinho'),
('Riacho dos Machados'),
('Ribeirão Vermelho'),
('Rio Acima'),
('Rio Casca'),
('Rio das Mortes'),
('Rio do Prado'),
('Rio Espera'),
('Rio Manso'),
('Rio Paranaíba'),
('Rio Piracicaba'),
('Rio Pomba'),
('Rio Preto'),
('Rio Vermelho'),
('Ritápolis'),
('Rochedo de Minas'),
('Rodeiro'),
('Romaria'),
('Rosário da Limeira'),
('Rubelita'),
('Rubim'),
('Sabinópolis'),
('Sacramento'),
('Salto da Divisa'),
('Santa Bárbara do Leste'),
('Santa Bárbara do Monte Verde'),
('Santa Bárbara do Tugúrio'),
('Santa Cruz de Minas'),
('Santa Cruz de Salinas'),
('Santa Cruz do Escalvado'),
('Santa Efigênia de Minas'),
('Santa Fé de Minas'),
('Santa Helena de Minas'),
('Santa Juliana'),
('Santa Margarida'),
('Santa Maria de Itabira'),
('Santa Maria do Salto'),
('Santa Maria do Suaçuí'),
('Santa Rita de Caldas'),
('Santa Rita de Ibitipoca'),
('Santa Rita de Jacutinga'),
('Santa Rita de Minas'),
('Santa Rita do Itueto'),
('Santa Rita do Sapucaí'),
('Santa Rosa da Serra'),
('Santa Vitória'),
('Santana da Vargem'),
('Santana de Cataguases'),
('Santana de Pirapama'),
('Santana do Deserto'),
('Santana do Garambéu'),
('Santana do Jacaré'),
('Santana do Manhuaçu'),
('Santana do Paraíso'),
('Santana do Riacho'),
('Santana dos Montes'),
('Santo Antônio do Amparo'),
('Santo Antônio do Aventureiro'),
('Santo Antônio do Grama'),
('Santo Antônio do Itambé'),
('Santo Antônio do Jacinto'),
('Santo Antônio do Monte'),
('Santo Antônio do Retiro'),
('Santo Antônio do Rio Abaixo'),
('Santo Hipólito'),
('São Bento Abade'),
('São Brás do Suaçuí'),
('São Domingos das Dores'),
('São Domingos do Prata'),
('São Félix de Minas'),
('São Francisco de Paula'),
('São Francisco de Sales'),
('São Francisco do Glória'),
('São Geraldo'),
('São Geraldo da Piedade'),
('São Geraldo do Baixio'),
('São Gonçalo do Abaeté'),
('São Gonçalo do Pará'),
('São Gonçalo do Rio Abaixo'),
('São Gonçalo do Rio Preto'),
('São Gonçalo do Sapucaí'),
('São João Batista do Glória'),
('São João da Lagoa'),
('São João da Mata'),
('São João das Missões'),
('São João do Manhuaçu'),
('São João do Manteninha'),
('São João do Oriente'),
('São João do Pacuí'),
('São João do Paraíso'),
('São João Evangelista'),
('São Joaquim de Bicas'),
('São José da Barra'),
('São José da Safira'),
('São José da Varginha'),
('São José do Alegre'),
('São José do Divino'),
('São José do Goiabal'),
('São José do Jacuri'),
('São José do Mantimento'),
('São Miguel do Anta'),
('São Pedro da União'),
('São Pedro do Suaçuí'),
('São Pedro dos Ferros'),
('São Romão'),
('São Roque de Minas'),
('São Sebastião da Bela Vista'),
('São Sebastião da Vargem Alegre'),
('São Sebastião do Anta'),
('São Sebastião do Maranhão'),
('São Sebastião do Oeste'),
('São Sebastião do Paraíso'),
('São Sebastião do Rio Preto'),
('São Sebastião do Rio Verde'),
('São Thomé das Letras'),
('São Tiago'),
('São Tomás de Aquino'),
('São Vicente de Minas'),
('Sapucaí-Mirim'),
('Sardoá'),
('Sarzedo'),
('Sem-Peixe'),
('Senador Amaral'),
('Senador Cortes'),
('Senador Firmino'),
('Senador José Bento'),
('Senador Modestino Gonçalves'),
('Senhora de Oliveira'),
('Senhora do Porto'),
('Senhora dos Remédios'),
('Sericita'),
('Seritinga'),
('Serra Azul de Minas'),
('Serra da Saudade'),
('Serra do Salitre'),
('Serra dos Aimorés'),
('Serrania'),
('Serranópolis de Minas'),
('Serranos'),
('Serro'),
('Sete Lagoas'),
('Silveirânia'),
('Silvianópolis'),
('Simão Pereira'),
('Simonésia'),
('Sobrália'),
('Soledade de Minas'),
('Tabuleiro'),
('Taiobeiras'),
('Taparuba'),
('Tapira'),
('Tapiraí'),
('Taquaraçu de Minas'),
('Tarumirim'),
('Teixeiras'),
('Teófilo Otoni'),
('Timóteo'),
('Tiradentes'),
('Tiros'),
('Tocantins'),
('Tocos do Moji'),
('Toledo'),
('Tombos'),
('Três Corações'),
('Três Marias'),
('Três Pontas'),
('Tumiritinga'),
('Tupaciguara'),
('Turmalina'),
('Turvolândia'),
('Ubá'),
('Ubaí'),
('Ubaporanga'),
('Uberaba'),
('Uberlândia'),
('Umburatiba'),
('Unaí'),
('União de Minas'),
('Uruana de Minas'),
('Urucânia'),
('Urucuia'),
('Vargem Alegre'),
('Vargem Bonita'),
('Vargem Grande do Rio Pardo'),
('Varginha'),
('Varjão de Minas'),
('Várzea da Palma'),
('Varzelândia'),
('Vazante'),
('Verdelândia'),
('Veredinha'),
('Veríssimo'),
('Vermelho Novo'),
('Vespasiano'),
('Viçosa'),
('Vieiras'),
('Virginópolis'),
('Virgínia'),
('Virgolândia'),
('Visconde do Rio Branco'),
('Volta Grande'),
('Wenceslau Braz')
ON CONFLICT (name) DO NOTHING;
