// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxfxuhustsqedstxwltq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4Znh1aHVzdHNxZWRzdHh3bHRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTI2MjgsImV4cCI6MjA2NTA2ODYyOH0.4hxpK8V4lmCMqJrV4bnnHmEfHIqh7HuIu0ASG6QrcXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);